### PR TITLE
Add Xcode project

### PR DESCRIPTION
**Pull request by non-binary**
# Step 1

Let's create a new project using Xcode 9.4.1 in the repo directory `tester-swift-macstadium`.

1. Click on "Create a new Project."
2. Click on "Single-View Application" in the iOS section.
3. Fill out the following details as so:

- Product Name: `Project`
- Team: `No Team`
- Organization Name: `travisci`
- Organization Identifier: `com.travisci`
- Bundle Identifier: `com.travisci.project`
- Language: `Swift` (this is important)

And make sure:

- **Use Core Data** is **unchecked**.
- **Include Unit Tests** is **checked**.
- **Include UI Tests** is **checked**.

### CODE REVIEW

**Comment by non-binary** [comment]
Once the project is created, please open Terminal.app (search Spotlight or open `Applications/Utilities`) and find the directory `tester-swift-macstadium` wherever you cloned it.

Then:

```
cd tester-swift-macstadium
mv Project/ temp/
cd temp
mv * ../
mv .gitignore ../
mv .travis.yml ../
``

This is the standard in the teams I've worked on because it removes having to do things like `Project/Project.xcodeproj` as you can just reference `Project.xcodeproj` because it's at the root of the repository/working directory.

From there, please add, commit, and push these files to this branch.

**Comment by MariadeAnton** [comment]
image
 first part is a go, I think 🎉

**Comment by non-binary** [comment]
Oh, can you have it as "Project" with a capital "P" Sorry!

**Comment by MariadeAnton** [comment]
Fixed to a Capital P - thanks for spotting! 

I've just pushed the branch with _I believe_, everything on it - could you take a look?

**Comment by non-binary** [comment]
Looks good to me!

**Comment by non-binary** [comment]
I will need to write up the next set of instructions. I know it's late for you, so, we can do the next step in 10-15 minutes or continue on Monday (if that works better for you/is preferred). 😺 😴

**Comment by MariadeAnton** [comment]
Gotcha! If you write the next set of instructions today, I can take care of them on Monday morning 💪

**Comment by non-binary** [comment]
Sounds good!

**Comment by non-binary** [comment]
# Step 3

We'll start with implementing the Unit Tests. 

If you're unfamiliar with Xcode, please look at [this diagram](https://user-images.githubusercontent.com/29215368/41790691-5a784caa-7621-11e8-8bbb-128be3ed2d8c.jpg). [[source](http://mobbook.generalassemb.ly/week01/xcode.html)]

Please open the Xcode project and navigate to the `ProjectTests.swift` file. This file will most likely be in the `ProjectTests` file group in the Project Navigator (which is on the left side).

Replace everything inside `ProjectTests.swift` with:

```swift
//
//  ProjectTests.swift
//  ProjectTests
//
//  Created by María de Antón on 22/06/2018.
//  Copyright © 2018 travisci. All rights reserved.
//

import XCTest
@testable import Project

class ProjectTests: XCTestCase {
    
    func testExample() {
        let result = 10 * 6
        assert(result == 60, "Result of calculation is 60.")
    }
    
}
```

We've added one test case called `ProjectTests.testExample()` and it's guaranteed to pass. 

Then add, commit, and push these changes to this branch.

**Comment by non-binary** [comment]
Here's a breakdown of what's happening in that file in case you're interested:

- This file imports XCTest which is Apple's first party testing framework.

- `@testable import Project` imports our main target `Project` with the caveat that allows us to invoke internal (`internal`, `private`, etc) functions more easily while avoid having to mark every class and function we want to test as `public`. This isn't particularly important for such a small project but can be useful in bigger projects where you want the compiled binary to be more locked down but still need internal access to properly test components.

- Then we define a class called `ProjectTests` which is a subclass of `XCTestCase` and define a function called `testExample`. This test case does a simple math problem and compares the result of `10*6` to `int 60` asserting that the result of that comparison `result == 60` will be `true`.

**Comment by non-binary** [comment]
# Step 4

The next step would be to implement a simple UI test however it's been so long since I've done this, Apple's changed a lot of the tooling underneath this. We could maybe do a screen share to go through this process and try things. I have some ideas but I don't want to provide them as code snippets yet because I'm not 100% sure they'd compile/work properly.

Let me know when works for you!

**Comment by non-binary** [comment]
Awesome! So, let me know when you'd have time to pair on the UI testing component. I had a stat today so I'm not working but I'd like to do some more research before the call so I have a general idea how to make it happen. Are you free on Wednesday or Thursday? (Feel free to respond on Slack) :)

**Comment by non-binary** [comment]
^Our UI testing code is from https://www.swiftbysundell.com/posts/getting-started-with-xcode-ui-testing-in-swift / https://github.com/johnsundell/UITestingExample. Thanks John!

**Pull request merged**
